/// App-wide constants. All third-party keys are injected at build time via
/// --dart-define and default to empty placeholders so the project compiles and
/// runs before the accounts exist.
library;

const String vitaApiBaseUrl = String.fromEnvironment(
  'VITA_API_BASE_URL',
  defaultValue: 'http://127.0.0.1:8260',
);

const String vitaAppVersion = String.fromEnvironment(
  'VITA_APP_VERSION',
  defaultValue: '1.0.0',
);

/// RevenueCat public SDK key (from the RevenueCat dashboard).
const String revenueCatApiKey = String.fromEnvironment(
  'VITA_REVENUECAT_KEY',
  defaultValue: '',
);

/// Google OAuth web client ID (server-side audience). Required on Android to
/// receive a usable ID token; on iOS the app client ID from
/// GoogleService-Info.plist is used.
const String googleServerClientId = String.fromEnvironment(
  'VITA_GOOGLE_SERVER_CLIENT_ID',
  defaultValue: '',
);

const String supportEmail = String.fromEnvironment(
  'VITA_SUPPORT_EMAIL',
  defaultValue: 'dylan_xm@163.com',
);

const String appStoreUrl = String.fromEnvironment(
  'VITA_APP_STORE_URL',
  defaultValue: '',
);

const String playStoreUrl = String.fromEnvironment(
  'VITA_PLAY_STORE_URL',
  defaultValue: '',
);

const String privacyPolicyUrl = String.fromEnvironment(
  'VITA_PRIVACY_POLICY_URL',
  defaultValue: '',
);

const String termsOfServiceUrl = String.fromEnvironment(
  'VITA_TERMS_OF_SERVICE_URL',
  defaultValue: '',
);

// Firebase is used only for system push delivery. Values are the public app
// identifiers generated by FlutterFire/Firebase Console and are injected at
// build time so beta and production can use separate Firebase apps.
const String firebaseProjectId = String.fromEnvironment(
  'VITA_FIREBASE_PROJECT_ID',
  defaultValue: '',
);
const String firebaseApiKey = String.fromEnvironment(
  'VITA_FIREBASE_API_KEY',
  defaultValue: '',
);
const String firebaseMessagingSenderId = String.fromEnvironment(
  'VITA_FIREBASE_MESSAGING_SENDER_ID',
  defaultValue: '',
);
const String firebaseAndroidAppId = String.fromEnvironment(
  'VITA_FIREBASE_ANDROID_APP_ID',
  defaultValue: '',
);
const String firebaseIosAppId = String.fromEnvironment(
  'VITA_FIREBASE_IOS_APP_ID',
  defaultValue: '',
);
const String firebaseIosBundleId = String.fromEnvironment(
  'VITA_FIREBASE_IOS_BUNDLE_ID',
  defaultValue: '',
);
