#!/usr/bin/env bash
#
# Prepare the isolated HOME used by the App targets (`make app-run`, etc.).
#
# The App recipes run Flutter with HOME pointed at app/.home so that CocoaPods
# and Dart caches stay inside the repository. CocoaPods clones the pods that use
# a git source (purchases-hybrid-common, RevenueCat, ...) with the inherited
# HOME, so the GitHub proxy from the machine's ~/.gitconfig has to be mirrored
# into app/.home/.gitconfig to keep those clones reachable from mainland China.
#
# A stale proxy entry is worse than no entry at all: when the local proxy client
# (Clash/V2Ray/...) is not running, every clone fails with
#   Failed to connect to 127.0.0.1 port 10808
# before it ever reaches the network. The proxy port is therefore probed and the
# entry is only mirrored when it answers; otherwise the clone falls back to a
# direct connection.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOME_DIR="$APP_DIR/.home"
GITCONFIG="$HOME_DIR/.gitconfig"
mkdir -p "$HOME_DIR"

# GitHub endpoints CocoaPods clones from; keep in sync with the sections in the
# machine's ~/.gitconfig.
GITHUB_URLS="https://github.com https://raw.githubusercontent.com"

proxy_for() {
  git config --global --get "http.$1.proxy" 2>/dev/null || true
}

# Returns 0 when the proxy URL should be kept (reachable, or impossible to
# probe), 1 when it points at a dead local port and must be dropped.
proxy_is_reachable() {
  local url="$1" host_port host port
  [ -n "$url" ] || return 1
  # Can't probe without a port: keep the user's configuration untouched.
  command -v nc >/dev/null 2>&1 || return 0
  host_port="${url#*://}"       # strip scheme
  host_port="${host_port%%/*}"  # strip path
  host_port="${host_port##*@}"  # strip credentials
  host="${host_port%%:*}"
  port="${host_port##*:}"
  [ "$host" != "$port" ] || return 0
  nc -z -G 1 "$host" "$port" >/dev/null 2>&1
}

tmp_config="$(mktemp "${TMPDIR:-/tmp}/vita-gitconfig.XXXXXX")"
trap 'rm -f "$tmp_config"' EXIT

{
  echo "# Generated by app/scripts/prepare_home.sh -- do not edit by hand."
  echo "[http]"
  echo "	version = HTTP/1.1"
  for url in $GITHUB_URLS; do
    proxy="$(proxy_for "$url")"
    [ -n "$proxy" ] || continue
    if proxy_is_reachable "$proxy"; then
      echo "[http \"$url\"]"
      echo "	proxy = $proxy"
    else
      echo "⚠️  Git proxy $proxy (for $url) is unreachable; using a direct connection." >&2
    fi
  done
} > "$tmp_config"

mv "$tmp_config" "$GITCONFIG"
trap - EXIT
